### 成功取得名言列表
GET {{server}}/api/jessigod/sayings
Authorization: bearer jessi:bac

### 成功取得名言列表 (指定頁數)
GET {{server}}/api/jessigod/sayings?pageIndex=1&pageSize=2
Authorization: bearer jessi:bac

### 成功取得名言列表 (指定頁數)
GET {{server}}/api/jessigod/sayings?editorOnly=1
Authorization: bearer jessi:ik9byg

### 隨機取得名言
GET {{server}}/api/jessigod/random-saying
Authorization: bearer jessi:ik9byg

