name: Build and deploy image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: docker build --file Dockerfile --tag marco79423/paji:latest .
      # 建置和推送
      - name: Get Version
        run: |
          export VERSION=${GITHUB_REF#refs/*/}
          echo "::env VERSION=${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Push image
        run: |
          echo "::env VERSION=${{env.VERSION}}"
          
          docker push marco79423/paji:latest

          docker tag marco79423/paji:latest marco79423/paji:${{env.VERSION}}
          docker push marco79423/paji:${{env.VERSION}}
